---
title: "Spatial setup"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
```

```{r libraries, include=F}
# Load libraries
library(tidyverse)
library(sf)
library(tigris)
library(stringr)

# Load source
source(file.path(here::here(),"common.R"))

# Load shp 
ci_shp <- st_read(file.path(project_data_path, "raw", "data_EPSG_4326", "california_islands.shp"))

# Load US counties shp 
us_counties <- tigris::counties()

## Central CA counties 
ca_counties <- us_counties %>% 
  filter(GEOID %in% c('06083', '06111', '06037'))

## MPA Atlas 
mpa_atlas <- st_read(file.path(emlab_data_dir, "mpa-atlas", "mpatlas_20201223_clean", "mpatlas_20201223_clean.shp"))
```

## Channel Islands 

Setup spatial files for the project. The shapefile for the Channel Islands was created by California Department of Fish and Wildlife and was downloaded from [Stanford's Digital Repository](https://purl.stanford.edu/nd958xt7750).  

```{r}
# Convert the linestring to multilinestring
ci_multiline <- st_cast(ci_shp, "MULTILINESTRING")

# Buffer it by 0 to turn linestrings into polygons 
ci_buffer <- st_buffer(ci_multiline, dist = 0)

# Add names to the polygons (based on county id)
ci_polys <- ci_buffer %>% 
  mutate(poly_num = case_when(COUNTY_ID == 520 ~ 1,
                              COUNTY_ID == 530 ~ 2,
                              COUNTY_ID == 519 ~ 3,
                              COUNTY_ID == 527 | COUNTY_ID == 528 ~ 4,
                              COUNTY_ID == 556 | COUNTY_ID == 557 ~ 5,
                              COUNTY_ID == 570 ~ 6,
                              COUNTY_ID == 559 ~ 7,
                              COUNTY_ID == 576 ~ 8,
                              TRUE ~ 9),
         poly_id = case_when(COUNTY_ID == 520 ~ 'San Miguel',
                             COUNTY_ID == 530 ~ 'Santa Rosa',
                             COUNTY_ID == 519 ~ 'Santa Cruz',
                             COUNTY_ID == 527 | COUNTY_ID == 528 ~ 'Anacapa',
                             COUNTY_ID == 556 | COUNTY_ID == 557 ~ 'Santa Barbara',
                             COUNTY_ID == 570 ~ 'San Nicolas',
                             COUNTY_ID == 559 ~ 'Catalina',
                             COUNTY_ID == 576 ~ 'San Clemente',
                             TRUE ~ 'Farallons')) %>% 
  filter(poly_id != 'Farallons') %>% 
  group_by(poly_num, poly_id) %>% 
  summarize(geometry = st_union(geometry))

# Validate polygons 
ci_polys_valid <- st_make_valid(ci_polys)
ci_polys_valid <- st_as_sf(ci_polys_valid)

# Bounding box 
ci_bbox <- st_bbox(ci_polys_valid) #xmin -121, xmax = -118; ymin = 32.5, ymax=34.5

# Graph to check - looks pretty good 
ggplot() + 
  geom_sf(data = ca_counties, fill = NA) + 
  geom_sf(data = ci_polys_valid, aes(color = poly_id), fill=NA) + 
  theme_classic()
```

```{r save}
# Save the islands shapefile to project folder
st_write(ci_polys_valid, file.path(project_data_path, "processed", "spatial", "channel_islands.shp"))

# Convert geometry to wkt
ci_bq <- ci_polys_valid %>% 
  mutate(boundary = st_as_text(geometry)) %>% 
  st_set_geometry(NULL)

# Upload to BigQuery
library(bigrquery)

bq_table(project = "emlab-gcp", table = "channel_islands_boundaries", dataset = "boi_dive_project") %>%
  bq_table_upload(values = ci_bq, fields = ci_bq)
```

## MPAs

```{r}
# Channel Islands MPAs
ci_mpas <- mpa_atlas %>% 
  filter(country == 'USA' & 
           name %in% c('Channel Islands', 
                       'Anacapa Island',
                       'Footprint',
                       'Footprint (Anacapa Channel)',
                       'Scorpion',
                       'Scorpion (Santa Cruz Island)',
                       'Gull Island',
                       'Gull Island (Santa Cruz Island)',
                       'Carrington Point (Santa Rosa Island)',
                       'Skunk Point (Santa Rosa Island)',
                       'South Point',
                       'South Point (Santa Rosa Island)',
                       'Richardson Rock',
                       'Richardson Rock (San Miguel Island)',
                       'Judith Rock (San Miguel Island)',
                       'Harris Point',
                       'Harris Point (San Miguel Island)',
                       'Begg Rock (San Nicolas Island)',
                       'Arrow Point to Lion Head Point (Catalina Island)',
                       'Blue Cavern (Catalina Island) Offshore',
                       'Blue Cavern (Catalina Island) Onshore',
                       'Casino Point (Catalina Island)',
                       'Cat Harbor (Catalina Island)',
                       'Farnsworth Offshore (Catalina Island)',
                       'Farnsworth Onshore (Catalina Island)',
                       "Lover's Cove (Catalina Island)",
                       'Long Point (Catalina Island)',
                       'Santa Barbara Island',
                       'Painted Cave (Santa Cruz Island)')) %>% 
  dplyr::mutate(gov_type = ifelse(is.na(gov_type), "Federal", gov_type)) %>% 
  dplyr::select(mpa_id, name, mpa_type = designatio, status, status_yr = status_yea, 
                gov_type, no_take, fishing, area_km2 = calc_m_are) %>% 
  # Remove the "special closure" area, "fish habitat area" 
  filter(!mpa_id %in% c(7606, 8670))

# CI polygons
ci_polys <- st_read(file.path(project_data_path, "processed", "spatial", "channel_islands.shp")) %>% 
  filter(poly_id != 'San Clemente')

# Plot to check 
ci_fed <- ci_mpas %>% 
  filter(gov_type == 'Federal' & mpa_id != 8688) 

ci_nms <- ci_mpas %>% 
  filter(mpa_id == 8688)

ci_state <- ci_mpas %>% 
  filter(gov_type == 'State')

mpa_map <- ggplot() + 
  geom_sf(data = ci_polys, fill = NA, color = 'black') + 
  geom_sf(data = ci_nms, fill = NA, aes(color = mpa_type)) + 
  geom_sf(data = ci_fed, aes(fill = mpa_type), alpha = 0.4) + 
  geom_sf(data = ci_state, aes(fill = mpa_type), alpha = 0.6) + 
  scale_fill_manual(values = c('slategray3', 'tomato', 'darkcyan', 'firebrick')) +
  scale_color_manual(values = c('midnightblue')) + 
  labs(color = "",
       fill = 'Type') + 
  theme_bw() + 
  # move color legend under the fill legend 
  guides(color = guide_legend(order = 2),
         fill = guide_legend(order = 1, nrow = 2)) +
  theme(legend.margin=margin(0,0,0,0, unit="cm"),
        legend.position = 'bottom')
```

```{r refine-mpas, message=F, warning=F}
# Revise the no take designation for Fed. Conservation Area (some fishing allowed)
# Add column for island 
ci_mpas_labeled <- ci_mpas %>% 
  mutate(fishing = ifelse(mpa_type == 'Federal Marine Conservation Area', 'Some Restrictions', fishing)) %>% 
  mutate(no_take = ifelse(fishing == "No", "All", "Part")) %>%
  mutate(island = case_when(str_detect(name, "Anacapa") ~ "Anacapa",
                            str_detect(name, "Catalina") ~ "Catalina",
                            str_detect(name, "Santa Rosa") ~ "Santa Rosa",
                            str_detect(name, "Santa Cruz") ~ "Santa Cruz",
                            str_detect(name, "San Miguel") ~ "San Miguel",
                            str_detect(name, "Santa Barbara") ~ "Santa Barbara",
                            str_detect(name, "San Nicolas") ~ "San Nicolas",
                            name %in% c("Richardson Rock", "Harris Point") ~ "San Miguel",
                            name %in% c("Scorpion", "Gull Island") ~ "Santa Cruz",
                            name == "Channel Islands" ~ "Channel Islands",
                            name == "Footprint" ~ "Anacapa",
                            name == "South Point" ~ "Santa Rosa"))

# Save North CI only
north_ci_mpas <- ci_mpas_labeled %>% 
  filter(island %in% c("San Miguel", "Santa Rosa", "Santa Cruz", "Anacapa"))
```


```{r save-mpas}
# Save the mpa shapefile to project folder
st_write(ci_mpas_labeled, file.path(project_data_path, "processed", "spatial", "channel_islands_mpas.shp"))

# Save north ci mpas
st_write(north_ci_mpas, file.path(project_data_path, "processed", "spatial", "north_channel_islands_mpas.shp"))

# Save map 
ggsave(plot = mpa_map, filename = file.path(project_figure_path, "mpa_map.png"))
```



